import random
import time
import copy
import numpy as np

import nearestNeighbour
from readData import ReadData

start_time = time.time()


def run(size, dis_mat):
    """
    :parameter size - size of matrix
    :parameter dis_mat - matrix

    path_index - temporary path
    best_path - the best path from NN algorithm
    starting_numbers - list of a 10 random starting points

    path - the best available path which can be generated by NN algorithm for k-chances(10)
    :return: path
    """
    starting_numbers = []
    best_distance = 99999999
    for _ in range(0, 10):
        x = random.randint(0, size - 1)
        if x not in starting_numbers:
            starting_numbers.append(x)
    for start in starting_numbers:

        path, distance = nearestNeighbour.run(size,dis_mat,start)

        if distance < best_distance:
            best_distance = distance
            best_path = path
            print(best_distance)


    return best_path
